apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: STRICT # UNSET, DISABLE, PERMISIVE


# apiVersion: security.istio.io/v1beta1
# kind: PeerAuthentication
# metadata:
#   name: default
#   namespace: foo
# spec:
#   mtls:
#     mode: PERMISSIVE
# ---
# apiVersion: security.istio.io/v1beta1
# kind: PeerAuthentication
# metadata:
#   name: default
#   namespace: foo
# spec:
#   selector:
#     matchLabels:
#       app: vote-service
#   mtls:
#     mode: STRICT


# apiVersion: security.istio.io/v1beta1
# kind: PeerAuthentication
# metadata:
#   name: default
#   namespace: foo
# spec:
#   selector:
#     matchLabels:
#       app: vote-service
#   mtls:
#     mode: STRICT
#   portLevelMtls:
#     8080:
#       mode: DISABLE


# apiVersion: security.istio.io/v1beta1
# kind: PeerAuthentication
# metadata:
#   name: default
#   namespace: foo
# spec:
#   selector:
#     matchLabels:
#       app: finance
#   mtls:
#     mode: UNSET
#   portLevelMtls:
#     8080:
#       mode: DISABLE