# Prerequistes: 
# Need to deploy vote-service with version v1 & v2
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: vote-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vote-web
spec:
  hosts:
  - "*"
  gateways:
  - vote-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: vote-web.default.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vote-service
spec:
  hosts:
  - "*"
  gateways:
  - vote-gateway
  http:
  - match:
    - uri:
        prefix: "/vote/"
    route:
    - destination:
        host: vote-service.default.svc.cluster.local
        subset: v1
      weight: 80
    - destination:
        host: vote-service.default.svc.cluster.local
        subset: v2
      weight: 20
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: vote-service
spec:
  host: vote-service.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      loadBalancer:
        simple: RANDOM
  - name: v2
    labels:
      version: v2