apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vote-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: vote.com
    http:
      paths:
      - path: "/vote/*"
        backend:
          serviceName: vote-service
          servicePort: 8080
      - path: "/*"
        backend:
          serviceName: vote-web
          servicePort: 3000
