apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-web
  template:
    metadata:
      labels:
        app: vote-web
    spec:
      serviceAccountName: vote-web
      containers:
      - name: vote-web
        image: vote-web:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "512Mi"
            cpu: "512m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vote-web
  namespace: default