apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-service
  template:
    metadata:
      labels:
        app: vote-service
    spec:
      serviceAccountName: vote-service
      containers:
      - name: vote-service
        image: vote-service:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "64Mi"
            cpu: "128m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vote-service
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-web
  template:
    metadata:
      labels:
        app: vote-web
    spec:
      serviceAccountName: vote-web
      containers:
      - name: vote-web
        image: vote-web:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "512Mi"
            cpu: "512m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vote-web
  namespace: default

# Vote Service with v1 and v2
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: vote-service-v1
#   namespace: default
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: vote-service
#       version: v1
#   template:
#     metadata:
#       labels:
#         app: vote-service
#         version: v1
#     spec:
#       serviceAccountName: vote-service
#       containers:
#       - name: vote-service
#         image: vote-service:v1
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
#         ports:
#         - containerPort: 8080
#         imagePullPolicy: Never
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: vote-service-v2
#   namespace: default
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: vote-service
#       version: v2
#   template:
#     metadata:
#       labels:
#         app: vote-service
#         version: v2
#     spec:
#       serviceAccountName: vote-service
#       containers:
#       - name: vote-service
#         image: vote-service:v2
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
#         ports:
#         - containerPort: 8080
#         imagePullPolicy: Never
